Repository kommitters/bas_use_cases, pull requests merged in 2025-08, with the labels that each got.

#195 Prepare release v1.10.1
  CHANGELOG.md
Labels: 🚀 Next release

#206 Add fetch bot for Notion key performance
  .env.example
  db/warehouse_migrations/20250814120124_update_kpis_columns.rb
  spec/use_cases_execution/google_workspace/env_helper.rb
  src/implementations/fetch_records_from_notion_database.rb
  src/implementations/warehouse_ingester.rb
  src/use_cases_execution/schedules.rb
  src/use_cases_execution/warehouse/config.rb
  src/use_cases_execution/warehouse/notion/fetch_kpis.rb
  src/use_cases_execution/warehouse/warehouse_ingester.rb
  src/utils/warehouse/notion/kpi_formatter.rb
Labels: 👍 Feature

#212 Resolve data saving issue in Warehouse Ingester
  src/implementations/warehouse_ingester.rb
Labels: 🐞 Bug

#216 Migrate Key Results bot to Google Workspace
  spec/use_cases_execution/google_workspace/listen_to_google_key_results_file_spec.rb
  src/use_cases_execution/use_cases_webserver/Google-key-result-script.md
  src/use_cases_execution/use_cases_webserver/app.rb
  src/use_cases_execution/warehouse/google_workspace/listen_to_google_key_results_file.rb
  src/use_cases_execution/warehouse/warehouse_ingester.rb
  src/utils/warehouse/google_workspace/key_results_format.rb
Labels: 👍 Feature
